name: web

on:
  push:
    branches:
    - test-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
          registry-url: https://npm.pkg.github.com/
      - name: bump version
        working-directory: statics
        uses: opspresso/action-version@v0.2.5
      - name: build & publish
        run: |
          npm ci
          npm run build
          npm publish --access public
        working-directory: statics
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
