name: web

on:
  push:
    branches:
    - test-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        name: build & publish
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci
          npm run build
          npm publish --access public
        working-directory: statics
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
