name: pim-web

on:
  push:
    branches:
    - master
    paths:
      - 'statics/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
          registry-url: https://npm.pkg.github.com/
      - name: build & publish
        run: |
          npm ci
          npm version patch
          npm run build
          npm publish
        working-directory: statics
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
